on: [pull_request]
name: publish package CI

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # we need to setup user email & name to be able to build the package: https://github.com/fregante/setup-git-user
      - name: Setup User
        uses: fregante/setup-git-user@v1

      - name: Build Package
        run: yarn build

      - name: Publish Package
        run: yarn publish
        # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#authenticating-to-the-destination-repository
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
