on: [pull_request]
name: publish package CI

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm build
